name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
    - name: Run Cypher
      id: cypher
      uses: cbastn/cypher-shell-docker@v1
      with:
          address: 'neo4j+s://1affca72.databases.neo4j.io'
          username: 'neo4j'
          password: 's3-HFzOriBZq-9jMUjhQ98wTLJC6p2Sa1PGlTDWsxM0'
          file: './SampleDbCreate.cypher'
