name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
    - name: Run Cypher
      id: cypher
      uses: cbastn/cypher-shell-docker@d8d49cebe48364af6fab8e345111080c93e4274d
      with:
          address: ${{ secrets.ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          file: | 
                './Sample.cypher'
                '.testFile.cypher'
                '.testFile1.cypher'
