name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
    - name: Run Cypher
      id: cypher
      uses: cbastn/cypher-shell-docker@v3
      env: 
        ADDRESS: ${{ secrets.ADDRESS }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
          address: "$ADDRESS"
          username: "$USERNAME"
          password: "$PASSWORD"
          file: './Sample.cypher'
